development:
  adapter: postgresql
  encoding: unicode
  database: artcreace_development
  pool: 5
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: artcreace_test
  pool: 5
  username: postgres
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: artcreace_production
  pool: 5
  username: postgres
  password: 123
